# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: FIAP Tech Challenge 2

on:
  push:
    branches: [ "main" ] 

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: 'theraclides'        
        password: $ {{ secrets.DOCKERHUB_PASSWORD }}
